apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: im-lazy
build:
  artifacts:
  - image: yournamespaceapi
    context: Your.Namespace.Api
    docker:
      dockerfile: Dockerfile-skaffold
  - image: yournamespaceapi2
    context: yournamespaceapi2
    docker:
      dockerfile: Dockerfile-skaffold
  # - image: yournamespaceapi3
  #   context: yournamespaceapi3
  #   docker:
  #     dockerfile: Dockerfile-skaffold
  # - image: yournamespaceapi4
  #   context: yournamespaceapi4
  #   docker:
  #     dockerfile: Dockerfile-skaffold
  # - image: yournamespacewebclient
  #   context: web-client
  #   docker:
  #     dockerfile: Dockerfile-skaffold
deploy:
  kubectl:
    manifests:
    #- hosting/basic-auth-secret.yml
    #- hosting/debug-server.yml
    #- hosting/infra.yml
    - hosting/local-development-backend.yml
