apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
  - name: "9080"
    port: 9080
    targetPort: 9080
  - name: "9081"
    port: 9081
    targetPort: 9081
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
