apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2020-10-02T00:00:00Z
  labels:
    io.kompose.service: cadvisor-claim1
  name: cadvisor-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
