# //NOTE:
#   - build context is alongside the .sln file so we can build our containers using class libraries in other folders. This enables each project to contain its Dockerfile yet access the nearby folders

version: "3"
services:
  api:
    container_name: "yournamespaceapi"
    build:
      context: ./
      dockerfile: ./Your.Namespace.Api/Dockerfile
      args:
        hello: "world"
    restart: "unless-stopped"
    ports:
      - "9080:9080"
      - "9081:9081"
    volumes:
      - ${HOME}/.aspnet/https:/https
    # depends_on:
    #     - identityserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  identityserver:
    container_name: yournamespaceidentityserver
    build:
      context: ./
      dockerfile: ./Your.Namespace.IdentityServer/Dockerfile
      args:
        hello: "world"
    restart: "unless-stopped"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${HOME}/.aspnet/https:/https
    ports:
      - "9082:9082"
      - "9083:9083"
