apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: 2020-10-02T00:00:00Z
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3000
  selector:
    io.kompose.service: grafana
status:
  loadBalancer: {}
