apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: identityserver
  name: identityserver
spec:
  ports:
  - name: "9083"
    port: 9083
    targetPort: 9083
  - name: "9084"
    port: 9084
    targetPort: 9084
  selector:
    io.kompose.service: identityserver
status:
  loadBalancer: {}
