apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: identityserver
  name: identityserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: identityserver
      service: ambassador
  strategy:
    type: Recreate  
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: identityserver
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        image: identityserver
        name: yournamespaceidentityserver
        ports:
        - containerPort: 9083
        - containerPort: 9084
        resources: {}
        volumeMounts:
        - mountPath: /https
          name: identityserver-claim0
      restartPolicy: Always
      volumes:
      - name: identityserver-claim0
        persistentVolumeClaim:
          claimName: identityserver-claim0
status: {}
