apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: 2020-10-02T00:00:00Z
  labels:
    io.kompose.service: identityserver
  name: identityserver
spec:
  ports:
  - name: "9082"
    port: 9082
    targetPort: 9082
  - name: "9083"
    port: 9083
    targetPort: 9083
  selector:
    io.kompose.service: identityserver
  type: LoadBalancer
status:
  loadBalancer: {}
