apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2020-10-02T00:00:00Z
  labels:
    io.kompose.service: node-exporter-claim0
  name: node-exporter-claim0
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
