apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: promtail
    variant: headless
  name: promtail-headless
  namespace: monitoring
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 3101
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: promtail
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
