prometheus:
  enabled: true
  ingress: 
    enabled: true
    ingressClassName: nginx
    hosts: ["prometheus.yournamespacecluster.local"]
    paths: ["/"]
    pathType: ImplementationSpecific

  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "yournamespaceapi"
        scrape_interval: 5s
        # dns_sd_configs:
        #   - names:
        #       - "tasks.node-exporter"
        #     type: "A"
        #     port: 9100
        static_configs:
          - targets: ["yournamespaceapi-svc.default:9080"]
      - job_name: "alertmanagergotifybridge"
        scrape_interval: 5s
        static_configs:
          - targets: ["alertmanagergotifybridge-svc.infra:30002"]
      - job_name: "pushgateway"
        scrape_interval: 5s
        static_configs:
          - targets: ["pushgateway-svc.infra:9091"]
      - job_name: "loki"
        scrape_interval: 5s
        static_configs:
          - targets: ["lokistack:3100"]
      - job_name: "promtail"
        scrape_interval: 5s
        static_configs:
          - targets: ["promtailstacklokiwhatisthis:9080"]
    externalUrl: prometheus.yournamespacecluster.local
    routePrefix: "/"

alertmanager:
  enabled: true
  config:
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 10m
      receiver: 'system-administrators'
      routes:      
      - match_re:
          service: ^(.*)$
        receiver: 'system-administrators'
    receivers:
    - name: 'system-administrators'
      webhook_configs:
      - send_resolved: true
        url: "http://alertmanagergotifybridge-svc.infra:30002/gotify_webhook"
    - name: 'webhook-demo'
      webhook_configs:
      - send_resolved: true
        url: "http://localhost:9080/alerts"
      # email_configs:
      # - send_resolved: true
      #   to: 'operations-team@example.org'
      #   html: '<h1>something bad </h1>'
      #   text: 'something bad'
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts: ["alertmanager.yournamespacecluster.local"]
    paths: ["/"]
    pathType: ImplementationSpecific
  alertManagerSpec:
    externalUrl: "alertmanager.yournamespacecluster.local"
    routePrefix: /

grafana:
  enabled: true
  adminPassword: password
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: ["grafana.yournamespacecluster.local"]    
    path: /
  # config:
    # sections:
    #   server:
    #     root_url: http://yournamespacecluster.local/grafana

prometheusOperator: 
  tls:
    enabled: false
  clusterDomain: yournamespacecluster.local
  namespaces:
    releaseNamespace: true
    additional:
      - infra
